### ISSUE TITLE
Calculating Age when birthday is tomorrow

### ISSUE THREAD

**Issue by MRhyne1931** [bsiddiqui/get-age#1]
It looks like the logic is slightly off.  I try to calculate the age for someone when their birthday is tomorrow and it does not work correctly.  

var getAge = require("get-age")

console.log(getAge('1941-01-27'));

This returns 76.  However today is 2017-01-26 so it should tell me they are 75.  Am I missing something?

**Comment by bsiddiqui** [comment]
@MRhyne1931 you're right there was a bug because I wasn't using `.getUTCDate`, which means the day could be off by one.

Since `new Date()` creates a date at midnight UTC, local time could be previous day.

https://github.com/bsiddiqui/get-age/commit/b093fa87d1555f133b0e5173ebfb26acb90b14ab fixes this issue and I've already pushed a release to NPM
